apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gpu-sizer
  namespace: gpu-sizer
spec:
  to:
    kind: Service
    name: gpu-sizer
  port:
    targetPort: 3000
  tls:
    termination: edge
