name: Build, Tag, and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up variables
        id: vars
        run: echo "TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.TAG }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ env.TAG }}

      - name: Update Kubernetes deployment YAML
        run: |
          sed -i 's|ghcr.io/.*/ai-model-gpu-sizer:.*|ghcr.io/vhojan/ai-model-gpu-sizer:${{ env.TAG }}|' manifests/deployment.yaml

      - name: Pull latest changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main

      - name: Commit and push manifest changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add manifests/deployment.yaml
          git commit -m "Update image tag to ${{ env.TAG }}"
          git push
