name: Build, Tag, and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Pull latest changes
        run: git pull --rebase origin main

      - name: Set up variables
        id: vars
        run: echo "TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (linux/amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.TAG }}
            ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64

      - name: Update Kubernetes deployment YAML
        run: |
          sed -i 's|ghcr.io/.*/ai-model-gpu-sizer:.*|ghcr.io/vhojan/ai-model-gpu-sizer:${{ env.TAG }}|' manifests/deployment.yaml

      - name: Commit and push manifest changes
        run: |
          git add manifests/deployment.yaml
          git commit -m "Update image tag to ${{ env.TAG }}" || echo "No changes to commit"
          git push
