name: Build and Push to GHCR

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Patch Kubernetes manifest (optional)
        run: |
          IMAGE_TAG=$(date +%s)
          sed -i "s|ghcr.io/.*/ai-model-gpu-sizer:.*|ghcr.io/${{ github.repository }}:$IMAGE_TAG|" manifests/deployment.yaml
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add manifests/deployment.yaml
          git commit -m "Update image tag to $IMAGE_TAG"
          git push
